Weights:
  VGGT: './weights/model.pt'
  DBoW: './weights/ORBvoc.txt'
  SALAD: './weights/dino_salad.ckpt'
  DNIO: './weights/dinov2_vitb14_pretrain.pth'

Model:
  chunk_size: 60
  overlap: 30
  loop_chunk_size: 20 # imgs of loop chunk = 2 * loop_chunk_size
  loop_enable: True
  useDBoW: False
  delete_temp_files: True
  align_method: 'numba' # 'numba' or 'numpy', use 'numba' would be faster
  using_sim3: True # Using SIM(3) alignment if True, while using SE(3) alignment if False
  reference_frame_mid: False 
  sample_rate: 30
  # If reference_frame_mid == True, use the middle frame within the chunk as the 
  # reference frame to alleviate the scale drift when loop closure is not available.
  # Disable it for now cuz i found some bugs related to this feature [by deng on 09 Oct].
  
  IRLS:
    delta: 0.1
    max_iters: 5
    tol: 1e-9

  Pointcloud_Save:
    sample_ratio: 0.015
    conf_threshold_coef: 0.75 # conf_threshold = np.mean(confs) * conf_threshold_coef

Loop:
  DBoW:
    thresh: 0.034
    num_repeat: 3
    NMS: 25

  SALAD:
    image_size: [336, 336]
    batch_size: 32
    similarity_threshold: 0.7
    top_k: 5
    use_nms: True
    nms_threshold: 25

  SIM3_Optimizer:
    lang_version: 'cpp' 
    # choose between 'cpp' or 'python'. will auto set 'python' if c++ version has not installed
    max_iterations: 30
    lambda_init: 1e-6
